python_3.5:   
    image: python:3.5

    script:
        - pip install .
        - pip install pytest
        - cd tests
        - py.test

python_3.6:
    image: python:3.6

    script:
        - pip install .
        - pip install pytest
        - cd tests
        - py.test
