language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - TEST_TYPE="test"
    INSTALL_TYPE="test"
  - TEST_TYPE="test"
    INSTALL_TYPE="test_sdist"
jobs:
  include:
    - python: "3.7"
      env:
        - TEST_TYPE="precommit"
          INSTALL_TYPE="dev"
install:
  - ./.travis-data/install_script.sh
script:
  - ./.travis-data/test_script.sh
